#
# This is the main e4nu project Makefile.
# Machine specific flags and locations are read from 'make/Make.include'.
# Configuration options are read from 'make/Make.config' generated by the 'configure' script.
# 
# Author: Julia Tena Vidal, jtenavidal \at tauex.tau.ac.il
#

SHELL = /bin/sh
NAME = all
MAKEFILE = Makefile

include $(E4NUANALYSIS)/src/make/Make.include

# define composite targets

BUILD_TARGETS = print-make-info \
		make-bin-lib-dir \
		configuration \
		utilities 
# ...
# here add main targets to build

INSTALL_TARGETS =  print-makeinstall-info \
		   check-previous-installation \
		   make-install-dirs \
		   copy-install-files

all:     $(BUILD_TARGETS)
install: $(INSTALL_TARGETS)

print-make-info: FORCE
	@echo " "
	@echo " "
	@echo "***** Building E4NUANALYSIS from source tree at: $(E4NUANALYSIS)"
	@echo " "

print-makeinstall-info: FORCE
	@echo " "
	@echo " "
	@echo "***** Installing E4NUANALYSIS at $(E4NUANALYSIS_INSTALLATION_PATH)"
	@echo " "

make-bin-lib-dir: FORCE
	@echo " "
	@echo "** Creating E4NUAnalysis lib and bin directories..."
	cd ${E4NUANALYSIS} && \
	[ -d bin ] || mkdir bin && chmod 755 bin && \
	[ -d lib ] || mkdir lib && chmod 755 lib;

configuration: FORCE
	@echo " "
	@echo "** Building Configuration..."
	cd ${E4NUANALYSIS}/conf && \
	cd make && \
	cd ${E4NUANALYSIS}

utilities: FORCE
	@echo " "
	@echo "** Building Utilities..."
	cd ${E4NUANALYSIS}/src/utils && \
	cd make & \
	cd ${E4NUANALYSIS}

make-install-dirs: FORCE
	@echo " "
	@echo "** Creating directory structure for E4NUANALYSIS installation..."
	[ -d ${E4NUANALYSIS_INSTALLATION_PATH} ] || mkdir ${E4NUANALYSIS_INSTALLATION_PATH}
	cd ${E4NUANALYSIS_INSTALLATION_PATH}
	[ -d ${E4NUANALYSIS_BIN_INSTALLATION_PATH} ] || mkdir ${E4NUANALYSIS_BIN_INSTALLATION_PATH}
	[ -d ${E4NUANALYSIS_LIB_INSTALLATION_PATH} ] || mkdir ${E4NUANALYSIS_LIB_INSTALLATION_PATH}
	[ -d ${E4NUANALYSIS_INC_INSTALLATION_PATH} ] || mkdir ${E4NUANALYSIS_INC_INSTALLATION_PATH}
	mkdir ${E4NUANALYSIS_INC_INSTALLATION_PATH}/conf
	mkdir ${E4NUANALYSIS_INC_INSTALLATION_PATH}/src
	mkdir ${E4NUANALYSIS_INC_INSTALLATION_PATH}/src/utils

copy-install-files: FORCE	
	@echo " "
	@echo "** Copying libraries/binaries/headers to installation location..."
	cp ${E4NUANALYSIS_BIN_PATH}/* ${E4NUANALYSIS_BIN_INSTALLATION_PATH} && \
	cd ${E4NUANALYSIS}/conf && make install && cd .. \
	cd ${E4NUANALYSIS}/src/utils && make install && cd ../.. \
	cd ${E4NUANALYSIS}

clean: clean-files clean-dir clean-etc

clean-files: FORCE
	@echo " "
	@echo "** Cleaning ..."
	cd ${E4NUANALYSIS}/conf && make clean && cd .. \
	cd src/utils && make clean && cd ../../ \
	cd ${E4NUANALYSIS} && \
	[ ! -d ./bin ] || rm ./bin/* && \
	cd ${E4NUANALYSIS} && \

clean-dir: FORCE
	@echo "Deleting E4nu Analysis lib and bin directories..." && \
	cd ${E4NUANALYSIS} && \
	[ ! -d ./bin ] || rmdir ./bin && \
	[ ! -d ./lib ] || rmdir ./lib 

clean-etc: FORCE
	cd $(E4NUANALYSIS) && \
	rm -f ./*log && \
	cd ${E4NUANALYSIS}

distclean: FORCE
	@echo " "
	@echo "** Cleaning E4nu Analysis installation... "
	[ ! -d ${E4NUANALYSIS_INSTALLATION_PATH}/include/GENIE ] || rm -rf ${GENIE_COMPARISONS_INSTALLATION_PATH}/include/GENIE/
	cd ${E4NUANALYSIS}/conf/ && make distclean && cd .. && \
	cd src/utils && make distclean & cd ../.. && \

FORCE: 	
