SHELL = /bin/sh
NAME = all
MAKEFILE = Makefile

include $(E4NUANALYSIS)/src/make/Make.include

PACKAGE           = E4NuConf
DICTIONARY        = _ROOT_DICT_E4NuConf
LIBNAME           = libE4NuConf
EXTRA_EXT_LIBS    =

all     : rootcint lib
install : install-lib

include $(E4NUANALYSIS)/src/make/Make.targets

FORCE:
